
[toolchain]
channel = "1.79"
components = [
    "rust-src",
    "rustc-dev",
    "llvm-tools-preview",
    "clippy",
    "rustfmt",
    "miri",
    "cargo",
]
targets = [
    "wasm32-unknown-unknown",
    "x86_64-unknown-linux-musl",
    "x86_64-unknown-linux-gnu",
]
