[book]
authors = ["@sevki"]
language = "en"
multilingual = true
src = "docs"

# additional css https://raw.githubusercontent.com/oknotokcomputer/okcss/main/ok.css
[output.html]
additional-css = ["ok.css"]
theme = "docs/theme"
default-theme = "dark"
git-repository-url = "https://ok.software/ok/src"
preferred-dark-theme = "rust"

[preprocessor.svgbob]

[preprocessor.alerts]
