name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets: [
          wasm32-unknown-unknown
          # , x86_64-unknown-linux-gnu
        ]
        packages: [srclang
        # ,src-lsp-server, src-lsp-browser
        ]
        toolchains: [stable
        # , nightly
        ]

    container: gcr.io/crosvm-infra/crosvm_dev:latest

    steps:
    - name: Modify hosts file
      run: |
        echo "66.241.125.220 ok.software" >> /etc/hosts
    
    - uses: actions/checkout@v4
    - name: reinstall rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        . "/cache/cargo_home/env"
    - name: rustup update
      run: |
        rustup toolchain install ${{ matrix.toolchains }}
        rustup component add cargo
        rustup component add clippy
        rustup target add ${{ matrix.targets }}
        rustup update
    - name: Build ${{ matrix.packages }} for ${{ matrix.targets }}
      run: cargo build --verbose --target ${{ matrix.targets }} -p ${{ matrix.packages }}
    - name: Test ${{ matrix.packages }} for ${{ matrix.targets }}
      run: cargo test --verbose --target ${{ matrix.targets }} -p ${{ matrix.packages }}
