name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    env:
      MDBOOK_VERSION: 0.4.40

    runs-on: ubuntu-latest
    container: ghcr.io/sevki/devcontainer:main

    strategy:
      matrix:
        targets:
        - x86_64-unknown-linux-gnu
        - wasm32-unknown-unknown
        packages:
        - src-lang
        toolchains:
        - stable
        - nightly

    steps:
    - uses: actions/checkout@v4
    - name: rustup update
      run: |
        rustup toolchain install ${{ matrix.toolchains }}
        rustup component add cargo
        rustup component add clippy
        rustup component add rust-src
        rustup target add ${{ matrix.targets }}
        rustup update
    - name: Build ${{ matrix.packages }} for ${{ matrix.targets }}
      run: cargo build --verbose --target ${{ matrix.targets }} -p ${{ matrix.packages }}
    - name: Test ${{ matrix.packages }} for ${{ matrix.targets }}
      run: cargo test --verbose --target ${{ matrix.targets }} -p ${{ matrix.packages }}
