name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: ghcr.io/sevki/devcontainer:main
    strategy:
      matrix:
        targets: [
          wasm32-unknown-unknown
          # , x86_64-unknown-linux-gnu
        ]
        packages: [srclang
        # ,src-lsp-server, src-lsp-browser
        ]
        toolchains: [stable
        # , nightly
        ]

    steps:
    - name: Tailscale
      env: 
        TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      run: |
        export TAILSCALE_AUTHKEY=${{ secrets.TS_OAUTH_SECRET }}?preauthorized=true&ephemeral=true
        tailscaled --tun=userspace-networking &
        tailscale up --accept-dns --accept-routes --exit-node=100.97.123.100 --authkey=$TAILSCALE_AUTHKEY
    - uses: actions/checkout@v4
    - name: rustup update
      run: |
        rustup toolchain install ${{ matrix.toolchains }}
        rustup component add cargo
        rustup component add clippy
        rustup component add rust-src 
        rustup target add ${{ matrix.targets }}
        rustup update
    - name: Build ${{ matrix.packages }} for ${{ matrix.targets }}
      run: cargo build -Zbuild-std --verbose --target ${{ matrix.targets }} -p ${{ matrix.packages }}
    - name: Test ${{ matrix.packages }} for ${{ matrix.targets }}
      run: cargo test --verbose --target ${{ matrix.targets }} -p ${{ matrix.packages }}
